### PR TITLE
Support Python 2.6

### LINKED ISSUE #2: Python 2.6: OrderedDict fallback needed
``` python
Traceback (most recent call last):
  File ".tox/py26/bin/refile", line 7, in <module>
    from refile.cmdline import main
  File "/home/travis/build/jayvdb/urllib3/.tox/py26/lib/python2.6/site-packages/refile/cmdline.py", line 3, in <module>
    from . import engine
  File "/home/travis/build/jayvdb/urllib3/.tox/py26/lib/python2.6/site-packages/refile/engine.py", line 7, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict
```

https://travis-ci.org/jayvdb/urllib3/jobs/86768683

### PR DESCRIPTION
**Pull request by jayvdb**
Add tox and travis-ci builds

Closes #2.

### CODE REVIEW

**Comment by jayvdb** [comment]
Demo build at https://travis-ci.org/jayvdb/reFILE/builds/86773075

**Comment by Sean1708** [comment]
Looks good to me, thanks for taking the time to do this.

**Comment by jayvdb** [comment]
No worries.  Could I bother you for a release, so that this tool is easy to use in tox on py26?

**Comment by Sean1708** [comment]
Yeah, I'll see if I can fix that `pathlib` problem first. If I can't I'll tag a new release this weekend.

**Pull request merged**
